openapi: "3.0.0"
info:
  title: Tshirt Store API
  description: Complete API for an Ecommerce Application
  version: 1.0.0
  contact:
    email: adiga@nags.dev
    url: "https://nags.dev"

servers:
  - url: "{protocol}://localhost:4000/api/{version}"
    description: for local environment
    variables:
      version:
        enum:
          - v1
          - v2
        default: v1
      protocol:
        enum:
          - http
          - https
        default: http

components:
  securitySchemas:
    cookieAuth:
      type: apikey
      in: cookie
      name: token
    BearerAuth:
      type: http
      scheme: bearer

paths:
  /dummy:
    get:
      tags:
        - Home
      summary: Home page API
      responses:
        200:
          desciption: All good success
          content:
            application/json:
              schema:
                type: string
                example: "mystring"
        400:
          description: Bad request
        500:
          description: Internal server error
